database:
  type: SQLITE

cooldowns:
  daily: 86400   # 1 d
  weekly: 604800  # 7 d
  monthly: 2592000 # 30 d

time_limits:
  daily: 30   # 1d
  weekly: 604800  # 7 d
  monthly: 2592000 # 30 d

buy_quest:
  daily:
    enabled: true
    limit: 30
    cost:
      money: 2500
      # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
      items: []
  weekly:
    enabled: false
    limit: 1
    cost:
      money: 100000
      items: []
  monthly:
    enabled: false
    limit: 1
    cost:
      money: 200000
      items:
        - 'NETHER_STAR:1'

gui:
  main_menu:
    title: "&8&l        Centrum Zadań"
    size: 27
  daily_quests_menu:
    title: "&8       Twoje misje dzienne"
    size: 36
  weekly_quests_menu:
    title: "&8      Twoje misje tygodniowe"
    size: 36
  monthly_quests_menu:
    title: "&8      Twoje misje miesięczne"
    size: 36

