name: VenQuests
version: '1.0_2'
main: pl.drytcha.venquests.VenQuests
api-version: '1.20'
author: Drytcha
description: Zaawansowany plugin na misje oraz specjalną wędkę.
depend: [Vault]
softdepend: [ItemsAdder]

commands:
  venquests:
    description: Główna komenda administracyjna pluginu VenQuests.
    usage: /<command> [reload|reset|list|getrod]
    aliases: [vq]
    permission: venquests.admin
  misje:
    description: Otwiera menu misji.
    usage: /<command>
    aliases: [zadania, quests]
    permission: venquests.player.use

permissions:
  venquests.player.use:
    description: Umożliwia graczom otwieranie menu misji za pomocą /misje.
    default: true
  venquests.admin:
    description: Umożliwia administracji zarządzanie pluginem VenQuests.
    default: op

